spring:
  application:
    name: appointment-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: http://localhost:9008
              predicates:
                - Path=/book/**
          default-filters:
            - TokenRelay # Token relay filter appends the oauth (or jwt) token to request header before forwarding requests
  security:
    oauth2:
      client:
        provider:
          platform-auth-server:
            issuer-uri: http://127.0.0.1:9000
        registration:
          gateway-client:
            provider: platform-auth-server
            client-id: gateway-client
            client-secret: 8adLFE4RHIqYOXhB7ZLjgqdRJWAioTMzlblC8XyKrc8=
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9001/login/oauth2/code/gateway-client
            scope:
              - openid
              - profile
              - email
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: book-service
#              uri: http://localhost:9008
#              predicates:
#                - Path=/book/**
#              filters:
#                - TokenRelay
#            - id: auth_service
#              predicates:
#                - Path= /api/v1/account/**
#              uri: http://localhost:9001
#              filters:
#                - TokenRelay # Token relay filter appends the oauth (or jwt) token to request header before forwarding requests
#            - id: branch_service
#              predicates:
#                - Path= /api/v1/branch/**
#              uri: http://localhost:9002
#            - id: appointment_service
#              predicates:
#                - Path= /api/v1/appointment/**
#              uri: http://localhost:9003
#              filters:
#                - TokenRelay # Token relay filter appends the oauth (or jwt) token to request header before forwarding requests


app:
  open-api:
    info:
      title: Appointment API Gateway Service
      description: Appointment API Gateway Service
      version: 1.0.0
  cors:
    allowed-origins:
      - http://localhost:9001
    allowed-methods:
      - POST
      - GET
      - PUT
      - OPTIONS
      - DELETE
      - PATCH
    allowed-headers:
      - "*"
    max-age: 3600
  jwt:
    secret: "8adLFE4RHIqYOXhB7ZLjgqdRJWAioTMzlblC8XyKrc8="
  white-list:
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/auth-service/swagger-ui/**"
    - "/auth-service/v3/api-docs/**"
    - "/api/v1/account/**"
    - "/branch-service/swagger-ui/**"
    - "/branch-service/v3/api-docs/**"
    - "/appointment-service/swagger-ui/**"
    - "/appointment-service/v3/api-docs/**"
  admin-routes:
    - "/api/v1/branch/admin/**"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    doc-expansion: none
    urls:
      - name: gateway-service
        url: ${springdoc.api-docs.path}
      - name: auth-service
        url: http://localhost:9001/auth-service/v3/api-docs
      - name: branch-service
        url: http://localhost:9002/branch-service/v3/api-docs
      - name: appointment-service
        url: http://localhost:9003/appointment-service/v3/api-docs

server:
  port: 9001
logging:
  level:
    root: debug

